// One-off: generate the WP5 MUSIC=on bed — a low, sparse, loopable plucked
// bass and marimba track, ducked well under Saskia's narration. Saved to
// <RECORDINGS_DIR>/music/bed.mp3, with the prompt and licence logged
// alongside it in bed.json (CLAUDE.md rule 7). Served to the player by
// app/api/music. Run once; re-run only to regenerate the bed.
//
//   npx tsx scripts/music.mts

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

function loadEnvLocal() {
  const file = path.join(process.cwd(), ".env.local");
  let text: string;
  try {
    text = readFileSync(file, "utf8");
  } catch {
    return;
  }
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) process.env[key] = value;
  }
}
loadEnvLocal();

const key = (process.env.ELEVENLABS_API_KEY ?? "").trim();
if (!key) {
  console.error("ELEVENLABS_API_KEY missing from .env.local");
  process.exit(1);
}

const PROMPT =
  "Sparse instrumental underscore for a paper-collage documentary explainer: soft plucked upright bass and marimba only, warm and understated, gentle even tempo around 92 BPM, no drums, no percussion kit, no vocals, no melody hooks, wide open space between notes, seamlessly loopable, low mixed level throughout so it can sit under narration.";
const DURATION_MS = 30_000;

async function main() {
  console.log("[music] requesting from ElevenLabs music API...");
  let upstream = await fetch("https://api.elevenlabs.io/v1/music", {
    method: "POST",
    headers: { "xi-api-key": key, "content-type": "application/json", accept: "audio/mpeg" },
    body: JSON.stringify({ prompt: PROMPT, music_length_ms: DURATION_MS }),
  });

  let endpoint = "https://api.elevenlabs.io/v1/music";
  if (!upstream.ok) {
    const detail = await upstream.text().catch(() => "");
    console.warn(`[music] /v1/music -> ${upstream.status}: ${detail.slice(0, 300)}`);
    console.log("[music] falling back to /v1/sound-generation...");
    endpoint = "https://api.elevenlabs.io/v1/sound-generation";
    upstream = await fetch(endpoint, {
      method: "POST",
      headers: { "xi-api-key": key, "content-type": "application/json", accept: "audio/mpeg" },
      body: JSON.stringify({ text: PROMPT, duration_seconds: 22, prompt_influence: 0.3 }),
    });
  }

  if (!upstream.ok) {
    const detail = await upstream.text().catch(() => "");
    console.error(`[music] failed: ${upstream.status} ${detail.slice(0, 500)}`);
    process.exit(1);
  }

  const bytes = new Uint8Array(await upstream.arrayBuffer());
  const recordingsDir = path.resolve(process.cwd(), (process.env.RECORDINGS_DIR ?? "").trim() || "../tessera-recordings");
  const dir = path.join(recordingsDir, "music");
  mkdirSync(dir, { recursive: true });
  writeFileSync(path.join(dir, "bed.mp3"), bytes);
  writeFileSync(
    path.join(dir, "bed.json"),
    JSON.stringify(
      {
        prompt: PROMPT,
        endpoint,
        requestedDurationMs: endpoint.endsWith("/music") ? DURATION_MS : 22_000,
        bytes: bytes.length,
        licence:
          "Generated via the project's own ElevenLabs account (ELEVENLABS_API_KEY) under ElevenLabs' standard API terms of service; usage rights follow the Curation/CurationAI ElevenLabs subscription plan in effect at generation time, same as the Saskia narration tracks generated by this app. Not a third-party sample or stock track.",
        generatedAt: new Date().toISOString(),
      },
      null,
      2
    )
  );
  console.log(`[music] saved ${bytes.length} bytes to ${path.join(dir, "bed.mp3")}`);
}

main().catch((cause) => {
  console.error("[music] failed:", cause instanceof Error ? cause.stack ?? cause.message : cause);
  process.exit(1);
});
